// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: pb/route.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RouteClient is the client API for Route service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteClient interface {
	//对外提供添加服务
	AddRoute(ctx context.Context, in *RouteInfo, opts ...grpc.CallOption) (*Response, error)
	DeleteRoute(ctx context.Context, in *RouteId, opts ...grpc.CallOption) (*Response, error)
	UpdateRoute(ctx context.Context, in *RouteInfo, opts ...grpc.CallOption) (*Response, error)
	FindRouteByID(ctx context.Context, in *RouteId, opts ...grpc.CallOption) (*RouteInfo, error)
	FindAllRoute(ctx context.Context, in *FindAll, opts ...grpc.CallOption) (*AllRoute, error)
}

type routeClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteClient(cc grpc.ClientConnInterface) RouteClient {
	return &routeClient{cc}
}

func (c *routeClient) AddRoute(ctx context.Context, in *RouteInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/route.Route/AddRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) DeleteRoute(ctx context.Context, in *RouteId, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/route.Route/DeleteRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) UpdateRoute(ctx context.Context, in *RouteInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/route.Route/UpdateRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) FindRouteByID(ctx context.Context, in *RouteId, opts ...grpc.CallOption) (*RouteInfo, error) {
	out := new(RouteInfo)
	err := c.cc.Invoke(ctx, "/route.Route/FindRouteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) FindAllRoute(ctx context.Context, in *FindAll, opts ...grpc.CallOption) (*AllRoute, error) {
	out := new(AllRoute)
	err := c.cc.Invoke(ctx, "/route.Route/FindAllRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteServer is the server API for Route service.
// All implementations must embed UnimplementedRouteServer
// for forward compatibility
type RouteServer interface {
	//对外提供添加服务
	AddRoute(context.Context, *RouteInfo) (*Response, error)
	DeleteRoute(context.Context, *RouteId) (*Response, error)
	UpdateRoute(context.Context, *RouteInfo) (*Response, error)
	FindRouteByID(context.Context, *RouteId) (*RouteInfo, error)
	FindAllRoute(context.Context, *FindAll) (*AllRoute, error)
	mustEmbedUnimplementedRouteServer()
}

// UnimplementedRouteServer must be embedded to have forward compatible implementations.
type UnimplementedRouteServer struct {
}

func (UnimplementedRouteServer) AddRoute(context.Context, *RouteInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoute not implemented")
}
func (UnimplementedRouteServer) DeleteRoute(context.Context, *RouteId) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedRouteServer) UpdateRoute(context.Context, *RouteInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoute not implemented")
}
func (UnimplementedRouteServer) FindRouteByID(context.Context, *RouteId) (*RouteInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRouteByID not implemented")
}
func (UnimplementedRouteServer) FindAllRoute(context.Context, *FindAll) (*AllRoute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllRoute not implemented")
}
func (UnimplementedRouteServer) mustEmbedUnimplementedRouteServer() {}

// UnsafeRouteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteServer will
// result in compilation errors.
type UnsafeRouteServer interface {
	mustEmbedUnimplementedRouteServer()
}

func RegisterRouteServer(s grpc.ServiceRegistrar, srv RouteServer) {
	s.RegisterService(&Route_ServiceDesc, srv)
}

func _Route_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).AddRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/route.Route/AddRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).AddRoute(ctx, req.(*RouteInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/route.Route/DeleteRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).DeleteRoute(ctx, req.(*RouteId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_UpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).UpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/route.Route/UpdateRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).UpdateRoute(ctx, req.(*RouteInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_FindRouteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).FindRouteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/route.Route/FindRouteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).FindRouteByID(ctx, req.(*RouteId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_FindAllRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).FindAllRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/route.Route/FindAllRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).FindAllRoute(ctx, req.(*FindAll))
	}
	return interceptor(ctx, in, info, handler)
}

// Route_ServiceDesc is the grpc.ServiceDesc for Route service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Route_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "route.Route",
	HandlerType: (*RouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRoute",
			Handler:    _Route_AddRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _Route_DeleteRoute_Handler,
		},
		{
			MethodName: "UpdateRoute",
			Handler:    _Route_UpdateRoute_Handler,
		},
		{
			MethodName: "FindRouteByID",
			Handler:    _Route_FindRouteByID_Handler,
		},
		{
			MethodName: "FindAllRoute",
			Handler:    _Route_FindAllRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/route.proto",
}
