Name: pod.rpc
ListenOn: 0.0.0.0:8081
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: pod.rpc
Mode: dev
DatabaseConf:
  Type: mysql
  Path: "localhost"
  Port: 3306
  Config: charset=utf8mb4&parseTime=True&loc=Local
  DBName: simple_admin
  Username: root
  Password: "root123"
  MaxIdleConn: 10
  MaxOpenConn: 100
  LogMode: error
  LogZap: false

Log:
  ServiceName: podRpcLogger
  Mode: console
#  Path: /home/data/logs/core/rpc
  Encoding: json
  Level: info
  Compress: false
  KeepDays: 7
  StackCoolDownMillis: 100

RedisConf:
  Host: 192.168.1.3:6379
  Type: node

Prometheus:
  Host: 0.0.0.0
  Port: 4002
  Path: /metrics
