// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-pass/app/service/k8s/route/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/route/FindRouteById/id/:Id",
				Handler: FindRouteByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/route/AddRoute",
				Handler: AddRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/route/DeleteRouteById/id/:id",
				Handler: DeleteRouteByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/route/UpdateRoute",
				Handler: UpdateRouteHandler(serverCtx),
			},
		},
	)
}
