// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Id int64 `path:"id"`
}

type Delrequest struct {
	Id int64 `json:"id"`
}

type RouteInfo struct {
	Id     int64            `json:"id"`
	Method string           `json:"method"`
	Header map[string]*Pair `json:"header"`
	Get    map[string]*Pair `json:"get"`
	Post   map[string]*Pair `json:"post"`
	Body   string           `json:"body"`
	Url    string           `json:"url"`
}

type Pair struct {
	Key    string   `json:"key"`
	Values []string `json:"values"`
}

type Response struct {
	StatusCode int64            `json:"statusCode"`
	Header     map[string]*Pair `json:"header"`
	Body       string           `json:"body"`
}
