global:
  scrape_interval: 15s #默认15秒采集一次
  external_labels:
    monitor: 'simple-admin-monitor'
scrape_configs:
  #监控的服务
  - job_name: 'simple-admin-rpc'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: ['192.168.1.2:4001']
  #监控的服务
  - job_name: 'simple-admin-api'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: ['192.168.1.2:4000']

  - job_name: 'pod-rpc'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: [ '192.168.1.2:4002' ]
  - job_name: 'pod-api'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: [ '192.168.1.2:4003' ]
  - job_name: 'route-rpc'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: [ '192.168.1.2:4004' ]
  - job_name: 'svc-rpc'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: [ '192.168.1.2:4005' ]
  - job_name: 'volume-rpc'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
     - targets: [ '192.168.1.2:4007' ]
  - job_name: 'shop-search-api'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      # 这个可以改，但是需要每个服务能暴露访问到
      - targets: [ '192.168.1.107:9091' ]